### ISSUE TITLE
Clarify security properties mentioned in README

### ISSUE THREAD

**Issue by awnumar** [frymimori/c-hasher#6]
> OptiHash is a fast hashing algorithm to create secure and variable-sized checksums in C

Does this mean cryptographic security or is it talking about some uniformity guarantees?

Also later it says

> Efficient alternative to secure hashing algorithms at equivalent hash digest sizes

**Comment by frymimori** [comment]
The cryptographic security properties are mentioned in [README.md](https://github.com/optifry/c-optihash/blob/main/README.md).

It hasn't been verified with NIST testing or SMHasher.

It's secure against collisions within standard computational feasibility, input byte patterns, input length patterns and pre-imaging.

Digests are irreversible and randomized sufficiently with the avalanche effect.

Hashing is secure with bit masking and shifting truncation, salt and seeded entropy with integral constants.

The entire hashing algorithm is explained with comments in [optihash.c](https://github.com/optifry/c-optihash/blob/main/optihash.c).

**Comment by awnumar** [comment]
Is this a custom design? Has it been validated by anyone other than yourself for the security properties you mentioned?

**Comment by frymimori** [comment]
Yes, it's a new, unique hashing algorithm.

Aside from my own tests, it's awaiting feedback from various online cryptography communities.

**Comment by awnumar** [comment]
In that case it's best to remove claims of security and explicitly mention that there's currently been no formal review of the algorithm or code

**Comment by frymimori** [comment]
Claims of security will remain after minor changes with ample cryptanalysis and test results when v1.0.0 is available for purchase.

**Comment by woefulwabbit** [comment]
> Is this a custom design? Has it been validated by anyone other than yourself for the security properties you mentioned?

@awnumar A second preimage attack has been demonstrated
https://www.reddit.com/r/cryptography/comments/152cya1/comment/jsmy5ld/

**Comment by awnumar** [comment]
@frymimori please remove claims of security and add that there's been no formal security verification. At present the README is intentionally misleading users

These attacks wouldn't matter if the project was documented as a non-cryptographic hash

**Comment by frymimori** [comment]
Security properties are now clarified and I've released a new, secure `v1.0.0`.
